#!/usr/bin/env python3
"""Solve every (arch, instances, node_size, noc_size, trace_dir, layer)
combo against the grid generated by
scripts/tmp/generate_multinode_arch_sweep.py, in parallel via a
multiprocessing.Pool.

Per log/2026-07-30-tracegen-refactor-and-multinode-sweep-plan.md Part B.1.
Reuses tracegen.solve_and_cache_schedule (the same solve/cache path as
solve_schedules.py and scripts/tmp/solve_multinode_schedules.py), pointed
at each swept arch YAML. Writes to outputs/schedules/multinode_sweep/ (a
new tree, separate from outputs/schedules/multinode/'s existing
128-baseline results).

Empirically verified on a Delta gpuA100x4-interactive node (1 GPU,
--cpus-per-task=64 -- the account is GPU-type-only, so a GPU is requested
purely to satisfy the job_submit policy, matching
dump/scripts's archived run_full_sweep_array.slurm's own rationale; the
solve itself never touches the GPU): 8/16/24/32/48/64-way concurrent
Gurobi solves all completed with zero errors and near-flat wall-clock
time. An EARLIER test on the shared login node stalled badly at 16
workers -- that was login-node contention, not a real Gurobi license
ceiling.

A SEPARATE, more serious issue found 2026-07-30: a single process that
solves many DIFFERENT arch configs in sequence can start silently
misreporting genuinely feasible combos as infeasible -- confirmed by
comparing a fresh, single-purpose process (always correct) against a
long-lived process working through several configs (wrong past roughly
the second or third distinct config). This was not fixed by disposing
each Gurobi Model, nor by using multiprocessing's "spawn" start method
with worker reuse -- only spawning a genuinely fresh, NEVER-reused
process per combo (spawn context + maxtasksperchild=1) reproduced the
correct, fresh-process answer on every trial. That is why this driver
pays the cost of a full process spawn per combo instead of a worker
pool that reuses processes across many tasks -- it's not a performance
choice, it's required for correct results.

Always run with --dry-run first to see the total combo count. Infeasible
combos (e.g. an arch whose dataflow needs more resident capacity than a
given (instances, node_size, noc_size) provides) are expected and
recorded in summary.csv, not treated as sweep-ending errors.

Resume: summary.csv is opened in APPEND mode and is the record of every
combo ever attempted, any status -- not just successful ones. An earlier
version filtered only inside the worker (checking for a schedule JSON on
disk, which only a successful solve writes) and overwrote summary.csv
fresh each run; that meant a resumed run silently re-derived every
already-confirmed INFEASIBLE combo from scratch every time, which is most
of this grid. Combos already present in summary.csv (in any status) are
filtered out BEFORE dispatch now, so a resume only ever pays for combos
truly not yet attempted.
"""

from __future__ import annotations

import argparse
import csv
import json
import multiprocessing as mp
import pathlib
import re
import sys
import time
import traceback
from collections import Counter

sys.path.insert(0, "src")

from archmodels.trace import valid_layer_names

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
ARCHS = ("loas", "spinalflow", "ptb", "gustavsnn", "prosperity")
INSTANCE_COUNTS = (16, 64, 256, 1024)
KB, MB = 1024, 1024 * 1024
NODE_SIZES = (2 * KB, 4 * KB, 8 * KB, 16 * KB, 32 * KB)
NOC_SIZES = (512 * KB, 1 * MB, 2 * MB, 4 * MB)
TRACE_DIRS = ("vgg16_T4_all", "resnet19_T4_all")
DEFAULT_TRACE_ROOT = pathlib.Path("/u/yyu9/neuro_cache_trace/input_trace/loas")
ARCH_YAML_DIR = REPO_ROOT / "configs" / "arch" / "multinode_sweep"


def _size_tag(n: int) -> str:
    return f"{n // KB}kb"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--trace-root", default=str(DEFAULT_TRACE_ROOT))
    parser.add_argument("--cache-dir", default="outputs/schedules/multinode_sweep")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--workers", type=int, default=64)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Report the total combo count and exit without solving anything.",
    )
    return parser.parse_args()


def iter_layers(trace_root: pathlib.Path, trace_name: str):
    with open(trace_root / trace_name / "meta.json") as file:
        meta = json.load(file)
    names = list(meta["layers"])
    valid = set(valid_layer_names(meta))
    for index, name in enumerate(names):
        if name not in valid:
            continue
        next_cin = (
            meta["layers"][names[index + 1]][2]
            if index + 1 < len(names)
            else None
        )
        yield name, meta, next_cin


def build_combos(trace_root: pathlib.Path, cache_dir: pathlib.Path, force: bool):
    combos = []
    for trace_name in TRACE_DIRS:
        layers = list(iter_layers(trace_root, trace_name))
        for arch in ARCHS:
            for instances in INSTANCE_COUNTS:
                for node_size in NODE_SIZES:
                    for noc_size in NOC_SIZES:
                        for layer_name, meta, next_cin in layers:
                            combos.append({
                                "arch": arch, "instances": instances,
                                "node_size": node_size, "noc_size": noc_size,
                                "trace_dir": trace_name, "layer": layer_name,
                                "meta": meta, "next_cin": next_cin,
                                "cache_dir": str(cache_dir), "force": force,
                            })
    return combos


def _combo_key(d: dict) -> tuple:
    return (d["arch"], str(d["instances"]), str(d["node_size"]), str(d["noc_size"]), d["trace_dir"], d["layer"])


_DIR_RE = re.compile(r"^inst(\d+)_node(\d+)kb_noc(\d+)kb$")


def scan_solved_from_disk(cache_dir: pathlib.Path) -> list:
    """Every combo with a persisted schedule JSON, reconstructed from the
    directory layout (cache_dir/inst<N>_node<X>kb_noc<Y>kb/<arch>/<trace_dir>/<layer>.json).

    Needed alongside summary.csv, not instead of it: a schedule can exist on
    disk from a run whose own summary.csv write was interrupted or (in an
    earlier version) truncated, and re-discovering those via a directory
    scan is a filesystem walk -- no process spawn, no re-solve -- versus
    dispatching each one to a worker just to have it discover the same file
    itself (observed 2026-07-30: this alone was costing ~20 real minutes on
    ~4600 combos, since a spawn's cost is comparable to an actual solve's).
    """
    rows = []
    if not cache_dir.exists():
        return rows
    for inst_dir in cache_dir.iterdir():
        match = _DIR_RE.match(inst_dir.name)
        if not match or not inst_dir.is_dir():
            continue
        instances, node_kb, noc_kb = match.groups()
        node_size, noc_size = int(node_kb) * KB, int(noc_kb) * KB
        for json_path in inst_dir.glob("*/*/*.json"):
            arch, trace_dir, layer_file = json_path.parts[-3:]
            rows.append({
                "arch": arch, "instances": instances, "node_size": str(node_size),
                "noc_size": str(noc_size), "trace_dir": trace_dir, "layer": layer_file[:-len(".json")],
                "status": "OK",
            })
    return rows


def load_already_attempted(summary_path: pathlib.Path) -> set:
    """Every (arch, instances, node_size, noc_size, trace_dir, layer) already
    recorded in summary.csv, REGARDLESS of status. Infeasible/error outcomes
    never persist a schedule JSON (only a successful solve does), so without
    this, a resumed run would silently re-derive every already-confirmed
    INFEASIBLE combo from scratch every single time -- the majority of this
    grid, since most combos are infeasible. summary.csv is the only record
    of "already checked" for those."""
    attempted = set()
    if summary_path.exists():
        with open(summary_path, newline="") as fh:
            for row in csv.DictReader(fh):
                attempted.add(_combo_key(row))
    return attempted


def _solve_one(combo: dict) -> dict:
    """Worker entry point (top-level so it pickles for multiprocessing)."""
    import tracegen  # imported per-worker: cheap, and keeps this module Gurobi-free at import time

    arch, instances = combo["arch"], combo["instances"]
    node_tag, noc_tag = _size_tag(combo["node_size"]), _size_tag(combo["noc_size"])
    trace_name, layer_name = combo["trace_dir"], combo["layer"]
    # cache_dir passed to solve_and_cache_schedule below, which appends its
    # own /arch_name/trace_dir/layer.json -- do NOT also put arch in this
    # prefix (an earlier version did, so out_path here never matched what
    # got written, and skip-existing silently never skipped anything).
    cache_dir = pathlib.Path(combo["cache_dir"]) / f"inst{instances}_node{node_tag}_noc{noc_tag}"
    out_path = cache_dir / arch / trace_name / f"{layer_name}.json"

    row = {
        "arch": arch, "instances": instances, "node_size": combo["node_size"], "noc_size": combo["noc_size"],
        "trace_dir": trace_name, "layer": layer_name,
    }
    if out_path.exists() and not combo["force"]:
        row["status"] = "SKIPPED"
        return row

    arch_yaml = ARCH_YAML_DIR / f"{arch}_inst{instances}_node{node_tag}_noc{noc_tag}.yaml"
    dataflow_yaml = f"configs/dataflow/{arch}.yaml"
    t0 = time.time()
    try:
        artifact = tracegen.solve_and_cache_schedule(
            arch, str(arch_yaml), dataflow_yaml, trace_name, layer_name,
            combo["meta"], combo["next_cin"], cache_dir,
        )
        row["status"] = "OK"
        row["mode"] = artifact.mode
        row["dram_num_steps"] = artifact.dram_num_steps
    except ValueError as error:
        row["status"] = "INFEASIBLE"
        row["error"] = str(error)
    except Exception as error:
        row["status"] = "ERROR"
        row["error"] = f"{type(error).__name__}: {error}"
        traceback.print_exc()
    row["seconds"] = time.time() - t0
    return row


def main() -> int:
    args = parse_args()
    trace_root = pathlib.Path(args.trace_root)
    cache_dir = pathlib.Path(args.cache_dir)

    combos = build_combos(trace_root, cache_dir, args.force)
    cache_dir.mkdir(parents=True, exist_ok=True)
    summary_path = cache_dir / "summary.csv"
    fields = ["arch", "instances", "node_size", "noc_size", "trace_dir", "layer",
              "status", "mode", "dram_num_steps", "seconds", "error"]

    # Resume by filtering BEFORE dispatch, using summary.csv (every combo
    # ever attempted, any status) rather than only checking for a schedule
    # JSON on disk (only a successful solve writes one) -- otherwise a
    # resumed run re-derives every already-confirmed INFEASIBLE combo from
    # scratch, which is most of this grid. summary.csv is opened in APPEND
    # mode below, never truncated, so this record only grows across runs.
    already = load_already_attempted(summary_path) if not args.force else set()

    # Also reconcile against schedules already on disk: a run whose own
    # summary.csv write got interrupted (or, in an earlier version,
    # truncated) can leave solved JSONs with no matching CSV row. Recover
    # those for free via a directory scan and append them now, rather than
    # dispatching each to a worker just to have it rediscover its own file
    # -- a spawn's cost is comparable to an actual solve's, so that alone
    # cost ~20 minutes across ~4600 combos (observed 2026-07-30).
    recovered = scan_solved_from_disk(cache_dir)
    new_recovered = [r for r in recovered if _combo_key(r) not in already]
    if new_recovered and not args.force:
        write_header = not summary_path.exists()
        with open(summary_path, "a", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fields)
            if write_header:
                writer.writeheader()
            for r in new_recovered:
                writer.writerow({k: r.get(k, "") for k in fields})
        already |= {_combo_key(r) for r in new_recovered}
        print(f"Recovered {len(new_recovered)} already-solved combo(s) from disk (no spawn needed).")

    todo = combos if args.force else [c for c in combos if _combo_key(c) not in already]
    print(
        f"{len(combos)} combo(s) total: {len(ARCHS)} archs x {len(INSTANCE_COUNTS)} instance counts x "
        f"{len(NODE_SIZES)} node sizes x {len(NOC_SIZES)} noc sizes x {len(TRACE_DIRS)} trace dirs "
        f"x layers per trace dir (varies per network). {len(already)} already attempted, "
        f"{len(todo)} remaining."
    )
    if args.dry_run:
        return 0
    if not todo:
        print("Nothing left to do.")
        return 0

    write_header = not summary_path.exists() or args.force
    open_mode = "w" if (args.force or not summary_path.exists()) else "a"
    counts = {"OK": 0, "SKIPPED": 0, "INFEASIBLE": 0, "ERROR": 0}
    t0 = time.time()
    ctx = mp.get_context("spawn")
    with open(summary_path, open_mode, newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        if write_header:
            writer.writeheader()
        with ctx.Pool(args.workers, maxtasksperchild=1) as pool:
            for i, row in enumerate(pool.imap_unordered(_solve_one, todo, chunksize=1), 1):
                writer.writerow({field: row.get(field, "") for field in fields})
                file.flush()
                counts[row["status"]] += 1
                if i % 500 == 0 or i == len(todo):
                    print(f"  {i}/{len(todo)} done ({time.time() - t0:.0f}s elapsed)", flush=True)
    wall = time.time() - t0

    print(
        f"\nthis run: {counts['OK']} solved, {counts['SKIPPED']} skipped, {counts['INFEASIBLE']} infeasible, "
        f"{counts['ERROR']} errored in {wall:.1f}s ({args.workers} workers) -> {summary_path}",
        flush=True,
    )

    cumulative = Counter()
    with open(summary_path, newline="") as fh:
        for row in csv.DictReader(fh):
            cumulative[row["status"]] += 1
    print(
        f"cumulative across all runs: {cumulative['OK']} solved, {cumulative['INFEASIBLE']} infeasible, "
        f"{cumulative['ERROR']} errored, {sum(cumulative.values())}/{len(combos)} combos accounted for",
        flush=True,
    )
    return 1 if counts["ERROR"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
