arch:
  bitwidths:
    BW_WEIGHT: 8
    BW_PSUM: 16
    BW_VMEM: 32
    DRAM_LATENCY: 0.25
  single_node: false
  storage:
  - name: NodeLevel
    instances: 1024
    pe:
      num_pes: 16
    local_buffer:
      entries:
        weight: 15360
        psum: 512
        vmem: 512
  - name: NoCLevel
    entries:
      weight: 3932160
      psum: 131072
      vmem: 131072
    instances: 1
  - name: OffChip
    instances: 1
